name: Trivy Scan - Build and Scan Image

on:
  workflow_dispatch:
  push:
    branches: [ ci/image-scan-test ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -f install/docker/Dockerfile -t local/meshery:test .

      - name: Run Trivy scan on built image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'local/meshery:test'
          format: 'json'
          output: 'trivy-scan-results.json'

      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy-scan-results.json

