name: Trivy Container Image Scan

on:
  workflow_dispatch:
  push:
    branches: [ ci/image-scan-test ]

permissions:
  contents: read
  issues: write

jobs:
  build-and-scan:
    name: Build & Scan Container Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -f install/docker/Dockerfile -t local/meshery:test .

      - name: Run Trivy scan on built image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'local/meshery:test'
          format: 'json'
          output: 'trivy-scan-results.json'

      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy-scan-results.json

      - name: Create GitHub issues for critical/high vulnerabilities
        run: |
          jq -r '.Results[] | select(.Vulnerabilities != null) | .Vulnerabilities[] 
            | select(.Severity == "CRITICAL" or .Severity == "HIGH") 
            | "- [" + .Severity + "] " + .Title + " (" + .VulnerabilityID + ") in " + .PkgName + " - " + .Description' trivy-scan-results.json > summary.md

          if [ -s summary.md ]; then
            gh issue create --title "Trivy Report: Critical/High Vulnerabilities Found" --body "$(cat summary.md)"
          else
            echo "No CRITICAL or HIGH vulnerabilities found."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

